language: node_js
node_js:
  - "12"
jobs:
  include:
    - stage: npm release
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        email: npm@tabdigital.com.au
        api_key: $NPM_TOKEN
        skip_cleanup: true
        on:
          tags: true
          branch: master
